# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessot.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'kessot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckessot.proto\x12\x06kessot\" \n\x04\x41tom\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04word\x18\x02 \x01(\t\"\'\n\x08\x41rgument\x12\x0c\n\x04role\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"&\n\x04\x46\x61\x63t\x12\x1e\n\x04\x61rgs\x18\x01 \x03(\x0b\x32\x10.kessot.Argument\"4\n\x06\x43lause\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\r\x12\x1a\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x0c.kessot.Fact\"M\n\x04Rule\x12 \n\ndefinition\x18\x01 \x01(\x0b\x32\x0c.kessot.Fact\x12#\n\x0b\x65xpressions\x18\x02 \x03(\x0b\x32\x0e.kessot.Clause\"S\n\x07\x43oncept\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\r\x12\x1b\n\x05\x66\x61\x63ts\x18\x02 \x03(\x0b\x32\x0c.kessot.Fact\x12\x1b\n\x05rules\x18\x03 \x03(\x0b\x32\x0c.kessot.Rule\"F\n\x04\x42ody\x12\x1b\n\x05\x61toms\x18\x01 \x03(\x0b\x32\x0c.kessot.Atom\x12!\n\x08\x63oncepts\x18\x02 \x03(\x0b\x32\x0f.kessot.Conceptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATOM']._serialized_start=24
  _globals['_ATOM']._serialized_end=56
  _globals['_ARGUMENT']._serialized_start=58
  _globals['_ARGUMENT']._serialized_end=97
  _globals['_FACT']._serialized_start=99
  _globals['_FACT']._serialized_end=137
  _globals['_CLAUSE']._serialized_start=139
  _globals['_CLAUSE']._serialized_end=191
  _globals['_RULE']._serialized_start=193
  _globals['_RULE']._serialized_end=270
  _globals['_CONCEPT']._serialized_start=272
  _globals['_CONCEPT']._serialized_end=355
  _globals['_BODY']._serialized_start=357
  _globals['_BODY']._serialized_end=427
# @@protoc_insertion_point(module_scope)
